### ISSUE TITLE
Link in try it out section has expired

### ISSUE THREAD

**Issue by satyanktiwari** [intuit/benten#1]
Click on the Link given in try it out section for joining slack,
Create account page for #SLACK opens and displays below message
 "This invite link is no longer active.
Please check with the person who shared it with you to see if there's a new link available."

**Comment by sharathshashidhar** [comment]
Updated the link in the readMe. Please check it out. Thanks for the catch 👍

**Comment by DivakarUngatla** [comment]
Here is the new link updated in Read me as well

https://join.slack.com/t/bentenapp/shared_invite/enQtMzg3MTkwNjc1MDkxLWI2ZDkzZjVhNTk2ZThlMjRhNTg3ZTc5OGExYTk1MGZkYTQ3Yzg3NzAzYWQyYzM5ZThiMGE2Mjk2OGZlOWUzYzk

**Comment by satyanktiwari** [comment]
Thanks for the quick turnaround.
Tried it out looks interesting
