### ISSUE TITLE
Dialogflow list parameters  exception

### ISSUE THREAD

**Issue by rnidagal** [intuit/benten#4]
With BenTen,  Just curious if there has been any testing with Dialogflow list parameters or if this is just me that is experiencing these run-time errors (entirely possible that I'm doing something wrong with the Java code for my intent). I cannot seem to get it to successfully pass a DialogFlow parameter into BenTen through slack if the IsList checkbox is checked in dialog flow. unchecking that checkbox allows the code and the single string value to be passed and used successfully in my local testing. also, Looking at the mvn spring-boot console it seems to throw some run-time exceptions anytime Dialogflow sends a list parameter.

**Comment by DivakarUngatla** [comment]
Fixed in release `0.1.3`

You can extract list parameters using
```
List<String> list = 
           BentenMessageHelper.getParameterAsInteger(bentenMessage, "list");
```
